Repository tamdaz/crygen, pull requests merged in 2025-03, with the labels that each got.

#19 Add aliases, mixins, simplify `add_property`, fix bugs
  spec/alias_spec.cr
  spec/class/class_spec.cr
  spec/struct/struct_spec.cr
  src/modules/mixin.cr
  src/modules/property.cr
  src/types/alias.cr
  src/types/class.cr
  src/types/enum.cr
Labels: enhancement

#22 Improve alias spec
  spec/alias_spec.cr
Labels: improvement

#20 Delete redudant params and returns
  src/modules/annotation.cr
  src/modules/arg.cr
  src/modules/class_var.cr
  src/modules/comment.cr
  src/modules/instance_var.cr
  src/modules/method.cr
  src/modules/mixin.cr
  src/modules/property.cr
  src/modules/scope.cr
  src/types/alias.cr
  src/types/annotation.cr
  src/types/class.cr
  src/types/enum.cr
  src/types/libc.cr
  src/types/macro.cr
  src/types/method.cr
  src/types/module.cr
  src/types/struct.cr
Labels: documentation

#23 Delete the `build` step
  .github/workflows/ci.yml
Labels: improvement

#26 Test helpers for annotations.
  spec/annotation_spec.cr
Labels: improvement
